### ISSUE TITLE
Live conversion from QUA to Qiskit simulations

### ISSUE THREAD

**Issue by nulinspiratie** [qua-platform/qua-qsim#5]
While writing a QUA program, it would be highly useful to see its effect on a simulated quantum system in real time.

## Example
![Slide1](https://github.com/qua-platform/qua-qsim/assets/38335668/1347b8d3-bbf4-49e2-8c91-f56bfe61b748)

### Frontend details
- The code input and plots should be created using [Plotly Dash](https://dash.plotly.com/).
  Alternative suitable suggestions can also be propose, but bidirectional communication needs to be supported: the backend should be able to request an update on the frontend.
- An example of a Dash code editor is found at https://github.com/dawidkopczyk/dash-editor-components
- This feature can later be integrated into #4 

### simulation details
Here are useful APIs and programs used to generate the example:
- [Power Rabi program](https://github.com/qua-platform/qua-qsim/blob/main/test/test_rabi.py): This program is a single-dimensional sweep with one QUA variable `a`, and is a great program to verify the front-end.
- **Schedule Plotting**: The `schedules_to_plot` argument accepts a list of indices of schedules to plot. These plotting mechanisms behind this function should be called/cached and reshaped in the background to display the schedule as a function of the QUA variable value on the slider.
```
results = simulate_program(
        qua_program=prog,
        qua_config=transmon_pair_qua_config,
        qua_config_to_backend_map=config_to_transmon_pair_backend_map,
        backend=transmon_pair_backend,
        num_shots=10_000,
        schedules_to_plot=[0] <-------- here!
)
```
- **Results plotting**:  Once the results are fetched, they can be plot on the y-axis, with the values that the QUA variable will take on on the x-axis.
```
    # make sure no single point is different to expected within 0.1 tolerance
    q1_state_probabilities = np.array(results[0])
    q2_state_probabilities = np.array(results[0])
    amps = np.arange(start, stop, step)

    for i, result in enumerate(results):
        plt.plot(np.arange(start, stop, step), results[i], '.-', label=f"Simulated Q{i}")
        plt.ylim(-0.05, 1.05)
    plt.legend()
    plt.show()
```

## Open questions
- There are different levels of "real time". 
  - At a minimum, there should be a command that can be called that takes a QUA program, compiles and simulates it, and then displays a plot.
  - A step above this is a background process with an API that can receive a serialized QUA program and compile+simulate it
  - Another step above is that this background process watches a file for changes and then plots that.
  - What level of real time are we looking for?
- How to add the config to this live converter?
- Where should it plot the results? In the frontend web app or as a program?

**Comment by Piwakk** [comment]
Hi @nulinspiratie, just like #4, could I be assigned to the issue? Thanks!

**Comment by nulinspiratie** [comment]
Apologies, I thought I was supposed to add you to the PR. Fixed!
